/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_docshifter_modules_hifi_jbig2_Jbig2Library */

#ifndef _Included_com_docshifter_modules_hifi_jbig2_Jbig2Library
#define _Included_com_docshifter_modules_hifi_jbig2_Jbig2Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_docshifter_modules_hifi_jbig2_Jbig2Library
 * Method:    encodeImage
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_docshifter_modules_hifi_jbig2_Jbig2Library_encodeImage
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
